### ISSUE TITLE
激活码有重复的问题

### ISSUE THREAD

**Issue by MOFANCITY** [jingpeicomp/id-generator#1]
您好，现在激活码会生成重复，是什么问题呢？

**Comment by jingpeicomp** [comment]
是不是有多台负载，如果有多台负载的话，构造函数中传入的机器ID（machineId）需要不同
    /**
     * 构造函数
     *
     * @param machineId       机器ID, 如果有多个负载，那么机器ID需要不同
     * @param alphabetsString 字符集编码字符串, 应该是26个大写字符的乱序
     */
    public ActivationCodeGenerator(int machineId, String alphabetsString) {
        int maxMachineId = ~(-1 << machineBits);
        if (machineId > maxMachineId) {
            throw new IllegalArgumentException("Machine bits is " + machineBits
                    + ", so the max machine id is " + maxMachineId);
        }

        this.machineId = machineId;
        init();
        parseAlphabets(alphabetsString);
    }

**Comment by acefunny001** [comment]
感谢回复！ 

不好意思，我没说明白，我现在使用了SecureActivationCodeGenerator

之前设置序号号的时候，每次都是从0自增，现在改为10位随机数了，目前看 ，没出现重复卡密；

不知道是不是因为序列号原因引起的重复。

**Comment by jingpeicomp** [comment]
应该不是这个原因，你是每次使用码的时候都重新创建SecureActivationCodeGenerator对象吗？

**Comment by acefunny001** [comment]
其中，

密钥，counter，nonce是固定值； 

alphabet() 也是提前生成后，一直固定的值；

目前看，是 singleton，但系统重启，肯定就不一样了。

**Comment by jingpeicomp** [comment]
抱歉回复晚了，序号是不可以重复的。安全激活码的典型使用场景是这样的：
1. 系统生成一张权益卡（比如充值卡、会员卡等），以充值卡为例，这张卡在数据库应该是如下字段：唯一ID、卡号（一般是16位字母数字）、有效期、金额等
2. 把这张卡的唯一ID作为序号和卡号通过SecureActivationCodeGenerator进行加密得到激活码
3. 然后把卡号和激活码给用户即可

从理论上来说，也可以不用激活码，直接用uuid或者其它的随机串，然后把uuid和卡的绑定关系存储在数据库，用户使用时校验数据库的绑定关系。使用激活码的好处在于无效把激活码存储到数据库。
